service: ghost-convertkit-integration
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  convertkit-ghost:
    handler: src/index.handler
    environment:
      GHOST_API_KEY: ${env:GHOST_API_KEY}
      CONVERTKIT_API_KEY: ${env:CONVERTKIT_API_KEY}
    events:
      - httpApi:
          path: /
          method: get
