service: ghost-convertkit-integration
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  convertkit-ghost:
    handler: src/index.handler
    environment:
      GHOST_API_KEY: ${env:GHOST_API_KEY}
      GHOST_URL: ${env:GHOST_URL}
      CONVERTKIT_API_SECRET: ${env:CONVERTKIT_API_SECRET}
      CONVERTKIT_SEQUENCE_ID: ${env:CONVERTKIT_SEQUENCE_ID}
    events:
      - httpApi:
          path: /{proxy+}
          method: any
