service: ghost-convertkit-integration
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  convertkit-ghost:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
