org: remarcable
app: ghost-ck
service: ghost-convertkit-integration
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-warmup

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    GHOST_ADMIN_API_KEY: ${env:GHOST_ADMIN_API_KEY}
    GHOST_API_URL: ${env:GHOST_API_URL}
    CONVERTKIT_API_SECRET: ${env:CONVERTKIT_API_SECRET}
    CONVERTKIT_SEQUENCE_ID: ${env:CONVERTKIT_SEQUENCE_ID}

functions:
  ghost-ck-integration:
    handler: src/index.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any
